[package]
name = "hourai-web"
version = "0.1.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2018"

[dependencies]
hourai = { path = "../hourai" }
hourai-sql = { path = "../storage/sql" }
hourai-redis = { path = "../storage/redis" }
actix-web = "3.3"
serde = "1.0"
hyper = { features = ["client", "http2", "runtime"], version = "0.14" }
lazy_static = "1.4"
serde_urlencoded = "0.7"
serde_json = "1.0"
protobuf = "2.22"
