[package]
name = "hourai-feeds"
version = "0.1.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2018"

[dependencies]
hourai = { path = "../hourai" }
hourai-sql = { path = "../storage/sql" }
futures = { default-features = false, version = "0.3.12" }
serde = "1.0"
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
twilight-embed-builder = "0.3"
mr_splashy_pants = "0.1"

[dependencies.sqlx]
default-features = false
features = ["runtime-tokio-rustls", "postgres", "macros"]
version = "0.5.1"

[dependencies.tokio]
default-features = false
version = "1.0"
features = ["macros", "rt"]
