[package]
name = "hourai-validation"
version = "0.1.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
