version: "3.8"
services:
  hourai:
    image: james7132/hourai:latest
    container_name: hourai
    command: python launcher.py run bot
    restart: unless-stopped
    environment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=prod
    volumes:
      - ./hourai.jsonnet:/opt/hourai.jsonnet:ro
      - ./lists/:/opt/lists:ro
    expose:
      - 8080
    depends_on:
      - postgres
      - redis
      - andesite
  logger:
    image: james7132/hourai:logger
    container_name: logger
    restart: unless-stopped
    environment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=prod
    volumes:
      - ./hourai.jsonnet:/opt/hourai.jsonnet:ro
      - ./lists/:/opt/lists:ro
    depends_on:
      - postgres
      - redis
      - http-proxy
  http-proxy:
    image: twilightrs/http-proxy
    container_name: http-proxy
    restart: unless-stopped
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=warn
      - HOST=0.0.0.0
      - PORT=80
      - DISCORD_TOKEN=""
  nginx:
    image: james7132/hourai:latest-frontend
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/common
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - hourai
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hourai
      - POSTGRES_USER=hourai
      - POSTGRES_PASSWORD=ddDa
  redis:
    image: redis:6.0-alpine
    container_name: redis
    command: ["redis-server",
              "--appendonly", "yes",
              "--save", "900", "1",
              "--save", "300", "10",
              "--save", "60", "10000"]
    restart: unless-stopped
    volumes:
      - redis-data:/data
  andesite:
    image: natanbc/andesite:latest
    restart: unless-stopped
    container_name: andesite
    volumes:
      - ./andesite.conf:/andesite/application.conf
    expose:
      - 2333
volumes:
  db-data:
    name: "db-data"
  redis-data:
    name: "redis-data"
networks:
  default:

    name: "hourai"
