version: "3.8"
services:
  hourai:
    build:
      context: ../
      dockerfile: ../base
    container_name: hourai
    command: python launcher.py run bot
    restart: unless-stopped
    environment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=dev
    volumes:
      - ./hourai.jsonnet:/opt/hourai.jsonnet:ro
      - ./lists/:/opt/lists:ro
    expose:
      - 8080
    depends_on:
      - postgres
      - redis
      - andesite
  logger:
    build:
      context: ../
      dockerfile: ../logger/Dockerfile
    container_name: logger
    restart: unless-stopped
    environment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=prod
    volumes:
      - ./hourai.jsonnet:/opt/hourai.jsonnet:ro
      - ./lists/:/opt/lists:ro
    depends_on:
      - postgres
      - redis
  frontend-dev:
    image: node:14.3.0
    container_name: frontend-dev
    working_dir: /app
    command: npm run serve
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ../frontend:/app
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/common
    depends_on:
      - hourai
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hourai
      - POSTGRES_USER=hourai
      - POSTGRES_PASSWORD=ddDa
  redis:
    image: redis:6.0-alpine
    container_name: redis
    command: ["redis-server",
              "--appendonly", "yes",
              "--save", "900", "1",
              "--save", "300", "10",
              "--save", "60", "10000"]
    restart: unless-stopped
    volumes:
      - redis-data:/data
  andesite:
    image: natanbc/andesite:latest
    restart: unless-stopped
    container_name: andesite
    volumes:
      - ./andesite.conf:/andesite/application.conf
    expose:
      - 2333
volumes:
  db-data:
    name: "db-data"
  redis-data:
    name: "redis-data"
networks:
  default:
    name: "hourai"
