[package]
name = "hourai"
version = "0.1.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2018"

[[bin]]
name = "hourai"
path =  "src/main.rs"
test = false
bench = false

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[dependencies]
async-trait = "0.1.41"
byteorder = "1.3.4"
flate2 = "1.0.18"
mobc = "0.5.12"
futures = "0.3.7"
mobc-redis = "0.5.3"
num-derive = "0.3.2"
num-traits = "0.2.12"
protobuf = "2.18.0"
serde = "1.0.117"
serde_json = "1.0.59"
tokio = "0.2.22"
tracing = "0.1.21"
twilight-cache-inmemory = "0.2"
twilight-gateway = "0.2"
twilight-http = "0.2"
twilight-model = "0.2"
twilight-standby = "0.2"

[build-dependencies]
walkdir = "2.3.1"
protobuf-codegen-pure = "2.18.0"

[dependencies.sqlx]
default-features = false
features = ["runtime-tokio-rustls", "postgres", "macros"]
version = "0.4.0-beta.1"
